name: towermarket
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  equatable: ^2.0.3
  gap: ^2.0.0
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  shimmer: ^2.0.0
  towermarket_ui:
    path: packages/towermarket_ui
  towermarket_repository:
    path: packages/towermarket_repository
  towermarket_api_client:
    path: packages/towermarket_api_client
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - images/categories/
    - images/products/
