name: towermarket_admin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  towermarket_repository:
    path: ../packages/towermarket_repository
  towermarket_ui:
    path: ../packages/towermarket_ui
  towermarket_api_client:
    path: ../packages/towermarket_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true
